#[doc = r"Enumeration of all the interrupts."]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
#[repr(u16)]
pub enum Interrupt {
    #[doc = "1 - AXI_PERF_MON"]
    AXI_PERF_MON               = 1,
    #[doc = "2 - USB_DEVICE"]
    USB_DEVICE                 = 2,
    #[doc = "3 - SDIO_HOST"]
    SDIO_HOST                  = 3,
    #[doc = "4 - SPI2"]
    SPI2                       = 4,
    #[doc = "5 - SPI3"]
    SPI3                       = 5,
    #[doc = "6 - I2S0"]
    I2S0                       = 6,
    #[doc = "7 - I2S1"]
    I2S1                       = 7,
    #[doc = "8 - UHCI0"]
    UHCI0                      = 8,
    #[doc = "9 - UART0"]
    UART0                      = 9,
    #[doc = "10 - UART1"]
    UART1                      = 10,
    #[doc = "11 - UART2"]
    UART2                      = 11,
    #[doc = "12 - UART3"]
    UART3                      = 12,
    #[doc = "13 - LCD_CAM"]
    LCD_CAM                    = 13,
    #[doc = "14 - PWM0"]
    PWM0                       = 14,
    #[doc = "15 - PWM1"]
    PWM1                       = 15,
    #[doc = "16 - PWM2"]
    PWM2                       = 16,
    #[doc = "17 - PWM3"]
    PWM3                       = 17,
    #[doc = "18 - TWAI0"]
    TWAI0                      = 18,
    #[doc = "19 - TWAI0_TIMER"]
    TWAI0_TIMER                = 19,
    #[doc = "20 - TWAI1"]
    TWAI1                      = 20,
    #[doc = "21 - TWAI1_TIMER"]
    TWAI1_TIMER                = 21,
    #[doc = "22 - RMT"]
    RMT                        = 22,
    #[doc = "23 - I2C0"]
    I2C0                       = 23,
    #[doc = "24 - I2C1"]
    I2C1                       = 24,
    #[doc = "25 - TG0_T0_LEVEL"]
    TG0_T0_LEVEL               = 25,
    #[doc = "26 - TG0_T1_LEVEL"]
    TG0_T1_LEVEL               = 26,
    #[doc = "27 - TG0_WDT_LEVEL"]
    TG0_WDT_LEVEL              = 27,
    #[doc = "28 - TG1_T0"]
    TG1_T0                     = 28,
    #[doc = "29 - TG1_T1"]
    TG1_T1                     = 29,
    #[doc = "30 - TG1_WDT"]
    TG1_WDT                    = 30,
    #[doc = "31 - LEDC0"]
    LEDC0                      = 31,
    #[doc = "32 - LEDC1"]
    LEDC1                      = 32,
    #[doc = "33 - SYSTIMER_TARGET0"]
    SYSTIMER_TARGET0           = 33,
    #[doc = "34 - SYSTIMER_TARGET1"]
    SYSTIMER_TARGET1           = 34,
    #[doc = "35 - SYSTIMER_TARGET2"]
    SYSTIMER_TARGET2           = 35,
    #[doc = "36 - AHB_PDMA_IN_CH0"]
    AHB_PDMA_IN_CH0            = 36,
    #[doc = "37 - AHB_PDMA_IN_CH1"]
    AHB_PDMA_IN_CH1            = 37,
    #[doc = "38 - AHB_PDMA_IN_CH2"]
    AHB_PDMA_IN_CH2            = 38,
    #[doc = "39 - AHB_PDMA_IN_CH3"]
    AHB_PDMA_IN_CH3            = 39,
    #[doc = "40 - AHB_PDMA_IN_CH4"]
    AHB_PDMA_IN_CH4            = 40,
    #[doc = "41 - AHB_PDMA_OUT_CH0"]
    AHB_PDMA_OUT_CH0           = 41,
    #[doc = "42 - AHB_PDMA_OUT_CH1"]
    AHB_PDMA_OUT_CH1           = 42,
    #[doc = "43 - AHB_PDMA_OUT_CH2"]
    AHB_PDMA_OUT_CH2           = 43,
    #[doc = "44 - AHB_PDMA_OUT_CH3"]
    AHB_PDMA_OUT_CH3           = 44,
    #[doc = "45 - AHB_PDMA_OUT_CH4"]
    AHB_PDMA_OUT_CH4           = 45,
    #[doc = "46 - ASRC_CHNL0"]
    ASRC_CHNL0                 = 46,
    #[doc = "47 - ASRC_CHNL1"]
    ASRC_CHNL1                 = 47,
    #[doc = "48 - AXI_PDMA_IN_CH0"]
    AXI_PDMA_IN_CH0            = 48,
    #[doc = "49 - AXI_PDMA_IN_CH1"]
    AXI_PDMA_IN_CH1            = 49,
    #[doc = "50 - AXI_PDMA_IN_CH2"]
    AXI_PDMA_IN_CH2            = 50,
    #[doc = "51 - AXI_PDMA_OUT_CH0"]
    AXI_PDMA_OUT_CH0           = 51,
    #[doc = "52 - AXI_PDMA_OUT_CH1"]
    AXI_PDMA_OUT_CH1           = 52,
    #[doc = "53 - AXI_PDMA_OUT_CH2"]
    AXI_PDMA_OUT_CH2           = 53,
    #[doc = "54 - RSA"]
    RSA                        = 54,
    #[doc = "55 - AES"]
    AES                        = 55,
    #[doc = "56 - SHA"]
    SHA                        = 56,
    #[doc = "57 - ECC"]
    ECC                        = 57,
    #[doc = "58 - ECDSA"]
    ECDSA                      = 58,
    #[doc = "59 - KM"]
    KM                         = 59,
    #[doc = "60 - RMA"]
    RMA                        = 60,
    #[doc = "61 - GPIO"]
    GPIO                       = 61,
    #[doc = "62 - GPIO_INT1"]
    GPIO_INT1                  = 62,
    #[doc = "63 - GPIO_INT2"]
    GPIO_INT2                  = 63,
    #[doc = "64 - GPIO_INT3"]
    GPIO_INT3                  = 64,
    #[doc = "69 - CACHE"]
    CACHE                      = 69,
    #[doc = "70 - CPU_APM_M0"]
    CPU_APM_M0                 = 70,
    #[doc = "71 - CPU_APM_M1"]
    CPU_APM_M1                 = 71,
    #[doc = "72 - CPU_APM_M2"]
    CPU_APM_M2                 = 72,
    #[doc = "73 - CPU_APM_M3"]
    CPU_APM_M3                 = 73,
    #[doc = "74 - HP_MEM_APM_M0"]
    HP_MEM_APM_M0              = 74,
    #[doc = "75 - HP_MEM_APM_M1"]
    HP_MEM_APM_M1              = 75,
    #[doc = "76 - HP_MEM_APM_M2"]
    HP_MEM_APM_M2              = 76,
    #[doc = "77 - HP_MEM_APM_M3"]
    HP_MEM_APM_M3              = 77,
    #[doc = "78 - HP_MEM_APM_M4"]
    HP_MEM_APM_M4              = 78,
    #[doc = "79 - HP_MEM_APM_M5"]
    HP_MEM_APM_M5              = 79,
    #[doc = "84 - HP_APM_M0"]
    HP_APM_M0                  = 84,
    #[doc = "85 - HP_APM_M1"]
    HP_APM_M1                  = 85,
    #[doc = "86 - HP_APM_M2"]
    HP_APM_M2                  = 86,
    #[doc = "87 - HP_APM_M3"]
    HP_APM_M3                  = 87,
    #[doc = "88 - HP_APM_M4"]
    HP_APM_M4                  = 88,
    #[doc = "89 - HP_APM_M5"]
    HP_APM_M5                  = 89,
    #[doc = "90 - HP_APM_M6"]
    HP_APM_M6                  = 90,
    #[doc = "91 - HP_PERI0_PMS"]
    HP_PERI0_PMS               = 91,
    #[doc = "92 - HP_PERI1_PMS"]
    HP_PERI1_PMS               = 92,
    #[doc = "96 - LPI"]
    LPI                        = 96,
    #[doc = "97 - PMT"]
    PMT                        = 97,
    #[doc = "98 - SBD"]
    SBD                        = 98,
    #[doc = "99 - USB_OTG_HS"]
    USB_OTG_HS                 = 99,
    #[doc = "100 - USB_OTG_HS_ENDP_MULTI_PROC"]
    USB_OTG_HS_ENDP_MULTI_PROC = 100,
    #[doc = "101 - JPEG"]
    JPEG                       = 101,
    #[doc = "102 - PPA"]
    PPA                        = 102,
    #[doc = "103 - CORE0_TRACE"]
    CORE0_TRACE                = 103,
    #[doc = "104 - CORE1_TRACE"]
    CORE1_TRACE                = 104,
    #[doc = "105 - DMA2D_IN_CH0"]
    DMA2D_IN_CH0               = 105,
    #[doc = "106 - DMA2D_IN_CH1"]
    DMA2D_IN_CH1               = 106,
    #[doc = "107 - DMA2D_IN_CH2"]
    DMA2D_IN_CH2               = 107,
    #[doc = "108 - DMA2D_OUT_CH0"]
    DMA2D_OUT_CH0              = 108,
    #[doc = "109 - DMA2D_OUT_CH1"]
    DMA2D_OUT_CH1              = 109,
    #[doc = "110 - DMA2D_OUT_CH2"]
    DMA2D_OUT_CH2              = 110,
    #[doc = "111 - DMA2D_OUT_CH3"]
    DMA2D_OUT_CH3              = 111,
    #[doc = "113 - HP_SYSREG"]
    HP_SYSREG                  = 113,
    #[doc = "114 - PCNT0"]
    PCNT0                      = 114,
    #[doc = "115 - PCNT1"]
    PCNT1                      = 115,
    #[doc = "116 - HP_PAU"]
    HP_PAU                     = 116,
    #[doc = "117 - HP_PARLIO_RX"]
    HP_PARLIO_RX               = 117,
    #[doc = "118 - HP_PARLIO_TX"]
    HP_PARLIO_TX               = 118,
    #[doc = "134 - CORDIC"]
    CORDIC                     = 134,
    #[doc = "135 - ZERO_DET"]
    ZERO_DET                   = 135,
    #[doc = "136 - LP_WDT"]
    LP_WDT                     = 136,
    #[doc = "137 - LP_TIMER0"]
    LP_TIMER0                  = 137,
    #[doc = "138 - LP_TIMER1"]
    LP_TIMER1                  = 138,
    #[doc = "141 - PMU0"]
    PMU0                       = 141,
    #[doc = "142 - PMU1"]
    PMU1                       = 142,
    #[doc = "143 - LP_ANA"]
    LP_ANA                     = 143,
    #[doc = "144 - LP_ADC"]
    LP_ADC                     = 144,
    #[doc = "145 - LP_DAC"]
    LP_DAC                     = 145,
    #[doc = "146 - LP_GPIO"]
    LP_GPIO                    = 146,
    #[doc = "149 - LP_TOUCH"]
    LP_TOUCH                   = 149,
    #[doc = "150 - LP_TSENS"]
    LP_TSENS                   = 150,
    #[doc = "151 - LP_UART"]
    LP_UART                    = 151,
    #[doc = "154 - LP_TRNG"]
    LP_TRNG                    = 154,
    #[doc = "156 - LP_APM_M0"]
    LP_APM_M0                  = 156,
    #[doc = "157 - LP_APM_M1"]
    LP_APM_M1                  = 157,
    #[doc = "158 - LP_APM_M2"]
    LP_APM_M2                  = 158,
    #[doc = "159 - LP_APM_M3"]
    LP_APM_M3                  = 159,
    #[doc = "160 - LP_PERI0_PMS"]
    LP_PERI0_PMS               = 160,
    #[doc = "161 - LP_PERI1_PMS"]
    LP_PERI1_PMS               = 161,
    #[doc = "162 - LP_HUK"]
    LP_HUK                     = 162,
    #[doc = "164 - LP_AHB_PDMA_IN_CH0"]
    LP_AHB_PDMA_IN_CH0         = 164,
    #[doc = "165 - LP_AHB_PDMA_IN_CH1"]
    LP_AHB_PDMA_IN_CH1         = 165,
    #[doc = "166 - LP_AHB_PDMA_OUT_CH0"]
    LP_AHB_PDMA_OUT_CH0        = 166,
    #[doc = "167 - LP_AHB_PDMA_OUT_CH1"]
    LP_AHB_PDMA_OUT_CH1        = 167,
}
#[doc = r" TryFromInterruptError"]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[derive(Debug, Copy, Clone)]
pub struct TryFromInterruptError(());
impl Interrupt {
    #[doc = r" Attempt to convert a given value into an `Interrupt`"]
    #[inline]
    pub fn try_from(value: u8) -> Result<Self, TryFromInterruptError> {
        match value {
            1 => Ok(Interrupt::AXI_PERF_MON),
            2 => Ok(Interrupt::USB_DEVICE),
            3 => Ok(Interrupt::SDIO_HOST),
            4 => Ok(Interrupt::SPI2),
            5 => Ok(Interrupt::SPI3),
            6 => Ok(Interrupt::I2S0),
            7 => Ok(Interrupt::I2S1),
            8 => Ok(Interrupt::UHCI0),
            9 => Ok(Interrupt::UART0),
            10 => Ok(Interrupt::UART1),
            11 => Ok(Interrupt::UART2),
            12 => Ok(Interrupt::UART3),
            13 => Ok(Interrupt::LCD_CAM),
            14 => Ok(Interrupt::PWM0),
            15 => Ok(Interrupt::PWM1),
            16 => Ok(Interrupt::PWM2),
            17 => Ok(Interrupt::PWM3),
            18 => Ok(Interrupt::TWAI0),
            19 => Ok(Interrupt::TWAI0_TIMER),
            20 => Ok(Interrupt::TWAI1),
            21 => Ok(Interrupt::TWAI1_TIMER),
            22 => Ok(Interrupt::RMT),
            23 => Ok(Interrupt::I2C0),
            24 => Ok(Interrupt::I2C1),
            25 => Ok(Interrupt::TG0_T0_LEVEL),
            26 => Ok(Interrupt::TG0_T1_LEVEL),
            27 => Ok(Interrupt::TG0_WDT_LEVEL),
            28 => Ok(Interrupt::TG1_T0),
            29 => Ok(Interrupt::TG1_T1),
            30 => Ok(Interrupt::TG1_WDT),
            31 => Ok(Interrupt::LEDC0),
            32 => Ok(Interrupt::LEDC1),
            33 => Ok(Interrupt::SYSTIMER_TARGET0),
            34 => Ok(Interrupt::SYSTIMER_TARGET1),
            35 => Ok(Interrupt::SYSTIMER_TARGET2),
            36 => Ok(Interrupt::AHB_PDMA_IN_CH0),
            37 => Ok(Interrupt::AHB_PDMA_IN_CH1),
            38 => Ok(Interrupt::AHB_PDMA_IN_CH2),
            39 => Ok(Interrupt::AHB_PDMA_IN_CH3),
            40 => Ok(Interrupt::AHB_PDMA_IN_CH4),
            41 => Ok(Interrupt::AHB_PDMA_OUT_CH0),
            42 => Ok(Interrupt::AHB_PDMA_OUT_CH1),
            43 => Ok(Interrupt::AHB_PDMA_OUT_CH2),
            44 => Ok(Interrupt::AHB_PDMA_OUT_CH3),
            45 => Ok(Interrupt::AHB_PDMA_OUT_CH4),
            46 => Ok(Interrupt::ASRC_CHNL0),
            47 => Ok(Interrupt::ASRC_CHNL1),
            48 => Ok(Interrupt::AXI_PDMA_IN_CH0),
            49 => Ok(Interrupt::AXI_PDMA_IN_CH1),
            50 => Ok(Interrupt::AXI_PDMA_IN_CH2),
            51 => Ok(Interrupt::AXI_PDMA_OUT_CH0),
            52 => Ok(Interrupt::AXI_PDMA_OUT_CH1),
            53 => Ok(Interrupt::AXI_PDMA_OUT_CH2),
            54 => Ok(Interrupt::RSA),
            55 => Ok(Interrupt::AES),
            56 => Ok(Interrupt::SHA),
            57 => Ok(Interrupt::ECC),
            58 => Ok(Interrupt::ECDSA),
            59 => Ok(Interrupt::KM),
            60 => Ok(Interrupt::RMA),
            61 => Ok(Interrupt::GPIO),
            62 => Ok(Interrupt::GPIO_INT1),
            63 => Ok(Interrupt::GPIO_INT2),
            64 => Ok(Interrupt::GPIO_INT3),
            69 => Ok(Interrupt::CACHE),
            70 => Ok(Interrupt::CPU_APM_M0),
            71 => Ok(Interrupt::CPU_APM_M1),
            72 => Ok(Interrupt::CPU_APM_M2),
            73 => Ok(Interrupt::CPU_APM_M3),
            74 => Ok(Interrupt::HP_MEM_APM_M0),
            75 => Ok(Interrupt::HP_MEM_APM_M1),
            76 => Ok(Interrupt::HP_MEM_APM_M2),
            77 => Ok(Interrupt::HP_MEM_APM_M3),
            78 => Ok(Interrupt::HP_MEM_APM_M4),
            79 => Ok(Interrupt::HP_MEM_APM_M5),
            84 => Ok(Interrupt::HP_APM_M0),
            85 => Ok(Interrupt::HP_APM_M1),
            86 => Ok(Interrupt::HP_APM_M2),
            87 => Ok(Interrupt::HP_APM_M3),
            88 => Ok(Interrupt::HP_APM_M4),
            89 => Ok(Interrupt::HP_APM_M5),
            90 => Ok(Interrupt::HP_APM_M6),
            91 => Ok(Interrupt::HP_PERI0_PMS),
            92 => Ok(Interrupt::HP_PERI1_PMS),
            96 => Ok(Interrupt::LPI),
            97 => Ok(Interrupt::PMT),
            98 => Ok(Interrupt::SBD),
            99 => Ok(Interrupt::USB_OTG_HS),
            100 => Ok(Interrupt::USB_OTG_HS_ENDP_MULTI_PROC),
            101 => Ok(Interrupt::JPEG),
            102 => Ok(Interrupt::PPA),
            103 => Ok(Interrupt::CORE0_TRACE),
            104 => Ok(Interrupt::CORE1_TRACE),
            105 => Ok(Interrupt::DMA2D_IN_CH0),
            106 => Ok(Interrupt::DMA2D_IN_CH1),
            107 => Ok(Interrupt::DMA2D_IN_CH2),
            108 => Ok(Interrupt::DMA2D_OUT_CH0),
            109 => Ok(Interrupt::DMA2D_OUT_CH1),
            110 => Ok(Interrupt::DMA2D_OUT_CH2),
            111 => Ok(Interrupt::DMA2D_OUT_CH3),
            113 => Ok(Interrupt::HP_SYSREG),
            114 => Ok(Interrupt::PCNT0),
            115 => Ok(Interrupt::PCNT1),
            116 => Ok(Interrupt::HP_PAU),
            117 => Ok(Interrupt::HP_PARLIO_RX),
            118 => Ok(Interrupt::HP_PARLIO_TX),
            134 => Ok(Interrupt::CORDIC),
            135 => Ok(Interrupt::ZERO_DET),
            136 => Ok(Interrupt::LP_WDT),
            137 => Ok(Interrupt::LP_TIMER0),
            138 => Ok(Interrupt::LP_TIMER1),
            141 => Ok(Interrupt::PMU0),
            142 => Ok(Interrupt::PMU1),
            143 => Ok(Interrupt::LP_ANA),
            144 => Ok(Interrupt::LP_ADC),
            145 => Ok(Interrupt::LP_DAC),
            146 => Ok(Interrupt::LP_GPIO),
            149 => Ok(Interrupt::LP_TOUCH),
            150 => Ok(Interrupt::LP_TSENS),
            151 => Ok(Interrupt::LP_UART),
            154 => Ok(Interrupt::LP_TRNG),
            156 => Ok(Interrupt::LP_APM_M0),
            157 => Ok(Interrupt::LP_APM_M1),
            158 => Ok(Interrupt::LP_APM_M2),
            159 => Ok(Interrupt::LP_APM_M3),
            160 => Ok(Interrupt::LP_PERI0_PMS),
            161 => Ok(Interrupt::LP_PERI1_PMS),
            162 => Ok(Interrupt::LP_HUK),
            164 => Ok(Interrupt::LP_AHB_PDMA_IN_CH0),
            165 => Ok(Interrupt::LP_AHB_PDMA_IN_CH1),
            166 => Ok(Interrupt::LP_AHB_PDMA_OUT_CH0),
            167 => Ok(Interrupt::LP_AHB_PDMA_OUT_CH1),
            _ => Err(TryFromInterruptError(())),
        }
    }
}
#[cfg(feature = "rt")]
#[macro_export]
#[doc = r" Assigns a handler to an interrupt"]
#[doc = r""]
#[doc = r" This macro takes two arguments: the name of an interrupt and the path to the"]
#[doc = r" function that will be used as the handler of that interrupt. That function"]
#[doc = r" must have signature `fn()`."]
#[doc = r""]
#[doc = r" Optionally, a third argument may be used to declare interrupt local data."]
#[doc = r" The handler will have exclusive access to these *local* variables on each"]
#[doc = r" invocation. If the third argument is used then the signature of the handler"]
#[doc = r" function must be `fn(&mut $NAME::Locals)` where `$NAME` is the first argument"]
#[doc = r" passed to the macro."]
#[doc = r""]
#[doc = r" # Example"]
#[doc = r""]
#[doc = r" ``` ignore"]
#[doc = r" interrupt!(TIM2, periodic);"]
#[doc = r""]
#[doc = r" fn periodic() {"]
#[doc = r#"     print!(".");"#]
#[doc = r" }"]
#[doc = r""]
#[doc = r" interrupt!(TIM3, tick, locals: {"]
#[doc = r"     tick: bool = false;"]
#[doc = r" });"]
#[doc = r""]
#[doc = r" fn tick(locals: &mut TIM3::Locals) {"]
#[doc = r"     locals.tick = !locals.tick;"]
#[doc = r""]
#[doc = r"     if locals.tick {"]
#[doc = r#"         println!("Tick");"#]
#[doc = r"     } else {"]
#[doc = r#"         println!("Tock");"#]
#[doc = r"     }"]
#[doc = r" }"]
#[doc = r" ```"]
macro_rules ! interrupt { ($ NAME : ident , $ path : path , locals : { $ ($ lvar : ident : $ lty : ty = $ lval : expr ;) * }) => { # [allow (non_snake_case)] mod $ NAME { pub struct Locals { $ (pub $ lvar : $ lty ,) * } } # [allow (non_snake_case)] # [no_mangle] pub extern "C" fn $ NAME () { let _ = $ crate :: interrupt :: Interrupt :: $ NAME ; static mut LOCALS : self :: $ NAME :: Locals = self :: $ NAME :: Locals { $ ($ lvar : $ lval ,) * } ; let f : fn (& mut self :: $ NAME :: Locals) = $ path ; f (unsafe { & mut LOCALS }) ; } } ; ($ NAME : ident , $ path : path) => { # [allow (non_snake_case)] # [no_mangle] pub extern "C" fn $ NAME () { let _ = $ crate :: interrupt :: Interrupt :: $ NAME ; let f : fn () = $ path ; f () ; } } }
