#[doc = r"Enumeration of all the interrupts."]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
#[repr(u16)]
pub enum Interrupt {
    #[doc = "0 - WIFI_MAC"]
    WIFI_MAC = 0,
    #[doc = "1 - WIFI_MAC_NMI"]
    WIFI_MAC_NMI = 1,
    #[doc = "2 - WIFI_PWR"]
    WIFI_PWR = 2,
    #[doc = "3 - WIFI_BB"]
    WIFI_BB = 3,
    #[doc = "4 - BT_MAC"]
    BT_MAC = 4,
    #[doc = "5 - BT_BB"]
    BT_BB = 5,
    #[doc = "6 - BT_BB_NMI"]
    BT_BB_NMI = 6,
    #[doc = "7 - LP_TIMER"]
    LP_TIMER = 7,
    #[doc = "8 - COEX"]
    COEX = 8,
    #[doc = "9 - BLE_TIMER"]
    BLE_TIMER = 9,
    #[doc = "10 - BLE_SEC"]
    BLE_SEC = 10,
    #[doc = "12 - ZB_MAC"]
    ZB_MAC = 12,
    #[doc = "13 - PMU"]
    PMU = 13,
    #[doc = "14 - EFUSE"]
    EFUSE = 14,
    #[doc = "15 - LP_RTC_TIMER"]
    LP_RTC_TIMER = 15,
    #[doc = "16 - LP_WDT"]
    LP_WDT = 16,
    #[doc = "18 - LP_APM_M0"]
    LP_APM_M0 = 18,
    #[doc = "19 - FROM_CPU_INTR0"]
    FROM_CPU_INTR0 = 19,
    #[doc = "20 - FROM_CPU_INTR1"]
    FROM_CPU_INTR1 = 20,
    #[doc = "21 - FROM_CPU_INTR2"]
    FROM_CPU_INTR2 = 21,
    #[doc = "22 - FROM_CPU_INTR3"]
    FROM_CPU_INTR3 = 22,
    #[doc = "24 - TRACE"]
    TRACE = 24,
    #[doc = "25 - CACHE"]
    CACHE = 25,
    #[doc = "26 - CPU_PERI_TIMEOUT"]
    CPU_PERI_TIMEOUT = 26,
    #[doc = "27 - GPIO"]
    GPIO = 27,
    #[doc = "28 - GPIO_EXT"]
    GPIO_EXT = 28,
    #[doc = "29 - PAU"]
    PAU = 29,
    #[doc = "32 - HP_APM_M0"]
    HP_APM_M0 = 32,
    #[doc = "33 - HP_APM_M1"]
    HP_APM_M1 = 33,
    #[doc = "34 - HP_APM_M2"]
    HP_APM_M2 = 34,
    #[doc = "35 - HP_APM_M3"]
    HP_APM_M3 = 35,
    #[doc = "38 - MSPI"]
    MSPI = 38,
    #[doc = "40 - UART0"]
    UART0 = 40,
    #[doc = "41 - UART1"]
    UART1 = 41,
    #[doc = "42 - UART2"]
    UART2 = 42,
    #[doc = "43 - LEDC"]
    LEDC = 43,
    #[doc = "44 - USB_DEVICE"]
    USB_DEVICE = 44,
    #[doc = "46 - TG0_T0_LEVEL"]
    TG0_T0_LEVEL = 46,
    #[doc = "47 - TG0_T1_LEVEL"]
    TG0_T1_LEVEL = 47,
    #[doc = "48 - TG0_WDT_LEVEL"]
    TG0_WDT_LEVEL = 48,
    #[doc = "49 - TG1_T0_LEVEL"]
    TG1_T0_LEVEL = 49,
    #[doc = "50 - TG1_T1_LEVEL"]
    TG1_T1_LEVEL = 50,
    #[doc = "51 - TG1_WDT_LEVEL"]
    TG1_WDT_LEVEL = 51,
    #[doc = "52 - SYSTIMER_TARGET0"]
    SYSTIMER_TARGET0 = 52,
    #[doc = "53 - SYSTIMER_TARGET1"]
    SYSTIMER_TARGET1 = 53,
    #[doc = "54 - SYSTIMER_TARGET2"]
    SYSTIMER_TARGET2 = 54,
    #[doc = "62 - SPI2"]
    SPI2 = 62,
    #[doc = "63 - SHA"]
    SHA = 63,
    #[doc = "65 - ECDSA"]
    ECDSA = 65,
}
#[doc = r" TryFromInterruptError"]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[derive(Debug, Copy, Clone)]
pub struct TryFromInterruptError(());
impl Interrupt {
    #[doc = r" Attempt to convert a given value into an `Interrupt`"]
    #[inline]
    pub fn try_from(value: u8) -> Result<Self, TryFromInterruptError> {
        match value {
            0 => Ok(Interrupt::WIFI_MAC),
            1 => Ok(Interrupt::WIFI_MAC_NMI),
            2 => Ok(Interrupt::WIFI_PWR),
            3 => Ok(Interrupt::WIFI_BB),
            4 => Ok(Interrupt::BT_MAC),
            5 => Ok(Interrupt::BT_BB),
            6 => Ok(Interrupt::BT_BB_NMI),
            7 => Ok(Interrupt::LP_TIMER),
            8 => Ok(Interrupt::COEX),
            9 => Ok(Interrupt::BLE_TIMER),
            10 => Ok(Interrupt::BLE_SEC),
            12 => Ok(Interrupt::ZB_MAC),
            13 => Ok(Interrupt::PMU),
            14 => Ok(Interrupt::EFUSE),
            15 => Ok(Interrupt::LP_RTC_TIMER),
            16 => Ok(Interrupt::LP_WDT),
            18 => Ok(Interrupt::LP_APM_M0),
            19 => Ok(Interrupt::FROM_CPU_INTR0),
            20 => Ok(Interrupt::FROM_CPU_INTR1),
            21 => Ok(Interrupt::FROM_CPU_INTR2),
            22 => Ok(Interrupt::FROM_CPU_INTR3),
            24 => Ok(Interrupt::TRACE),
            25 => Ok(Interrupt::CACHE),
            26 => Ok(Interrupt::CPU_PERI_TIMEOUT),
            27 => Ok(Interrupt::GPIO),
            28 => Ok(Interrupt::GPIO_EXT),
            29 => Ok(Interrupt::PAU),
            32 => Ok(Interrupt::HP_APM_M0),
            33 => Ok(Interrupt::HP_APM_M1),
            34 => Ok(Interrupt::HP_APM_M2),
            35 => Ok(Interrupt::HP_APM_M3),
            38 => Ok(Interrupt::MSPI),
            40 => Ok(Interrupt::UART0),
            41 => Ok(Interrupt::UART1),
            42 => Ok(Interrupt::UART2),
            43 => Ok(Interrupt::LEDC),
            44 => Ok(Interrupt::USB_DEVICE),
            46 => Ok(Interrupt::TG0_T0_LEVEL),
            47 => Ok(Interrupt::TG0_T1_LEVEL),
            48 => Ok(Interrupt::TG0_WDT_LEVEL),
            49 => Ok(Interrupt::TG1_T0_LEVEL),
            50 => Ok(Interrupt::TG1_T1_LEVEL),
            51 => Ok(Interrupt::TG1_WDT_LEVEL),
            52 => Ok(Interrupt::SYSTIMER_TARGET0),
            53 => Ok(Interrupt::SYSTIMER_TARGET1),
            54 => Ok(Interrupt::SYSTIMER_TARGET2),
            62 => Ok(Interrupt::SPI2),
            63 => Ok(Interrupt::SHA),
            65 => Ok(Interrupt::ECDSA),
            _ => Err(TryFromInterruptError(())),
        }
    }
}
#[cfg(feature = "rt")]
#[macro_export]
#[doc = r" Assigns a handler to an interrupt"]
#[doc = r""]
#[doc = r" This macro takes two arguments: the name of an interrupt and the path to the"]
#[doc = r" function that will be used as the handler of that interrupt. That function"]
#[doc = r" must have signature `fn()`."]
#[doc = r""]
#[doc = r" Optionally, a third argument may be used to declare interrupt local data."]
#[doc = r" The handler will have exclusive access to these *local* variables on each"]
#[doc = r" invocation. If the third argument is used then the signature of the handler"]
#[doc = r" function must be `fn(&mut $NAME::Locals)` where `$NAME` is the first argument"]
#[doc = r" passed to the macro."]
#[doc = r""]
#[doc = r" # Example"]
#[doc = r""]
#[doc = r" ``` ignore"]
#[doc = r" interrupt!(TIM2, periodic);"]
#[doc = r""]
#[doc = r" fn periodic() {"]
#[doc = r#"     print!(".");"#]
#[doc = r" }"]
#[doc = r""]
#[doc = r" interrupt!(TIM3, tick, locals: {"]
#[doc = r"     tick: bool = false;"]
#[doc = r" });"]
#[doc = r""]
#[doc = r" fn tick(locals: &mut TIM3::Locals) {"]
#[doc = r"     locals.tick = !locals.tick;"]
#[doc = r""]
#[doc = r"     if locals.tick {"]
#[doc = r#"         println!("Tick");"#]
#[doc = r"     } else {"]
#[doc = r#"         println!("Tock");"#]
#[doc = r"     }"]
#[doc = r" }"]
#[doc = r" ```"]
macro_rules ! interrupt { ($ NAME : ident , $ path : path , locals : { $ ($ lvar : ident : $ lty : ty = $ lval : expr ;) * }) => { # [allow (non_snake_case)] mod $ NAME { pub struct Locals { $ (pub $ lvar : $ lty ,) * } } # [allow (non_snake_case)] # [no_mangle] pub extern "C" fn $ NAME () { let _ = $ crate :: interrupt :: Interrupt :: $ NAME ; static mut LOCALS : self :: $ NAME :: Locals = self :: $ NAME :: Locals { $ ($ lvar : $ lval ,) * } ; let f : fn (& mut self :: $ NAME :: Locals) = $ path ; f (unsafe { & mut LOCALS }) ; } } ; ($ NAME : ident , $ path : path) => { # [allow (non_snake_case)] # [no_mangle] pub extern "C" fn $ NAME () { let _ = $ crate :: interrupt :: Interrupt :: $ NAME ; let f : fn () = $ path ; f () ; } } }
