[workspace]
resolver = "2"
members  = ["xtask"]
exclude  = [
    "esp32",
    "esp32c2",
    "esp32c3",
    "esp32c6",
    "esp32c6-lp",
    "esp32h2",
    "esp32p4",
    "esp32s2",
    "esp32s2-ulp",
    "esp32s3",
    "esp32s3-ulp",
]
