#[doc = "Register `HCDMA13` reader"]
pub type R = crate::R<HCDMA13_SPEC>;
#[doc = "Register `HCDMA13` writer"]
pub type W = crate::W<HCDMA13_SPEC>;
#[doc = "Field `DMAADDR` reader - In Buffer DMA Mode: \\[31:0\\]: DMA Address (DMAAddr) This field holds the start address in the external memory from which the data for the endpoint must be fetched or to which it must be stored. This register is incremented on every AHB transaction. Reset: X if not programmed as the register is in SPRAM. In Scatter-Gather DMA (DescDMA) Mode for Non-Isochronous: \\[31:9\\]: DMA Address (DMAAddr) The start address must be 512-bytes aligned. This field holds the start address of the 512 bytes page. The first descriptor in the list must be located in this address. The first descriptor may be or may not be ready. The core starts processing the list from the CTD value. \\[8:3\\]: Current Transfer Desc(CTD) This value is in terms of number of descriptors. The values can be from 0 to 63. - 0 - 1 descriptor. - 63 - 64 descriptors. This field indicates the current descriptor processed in the list. This field is updated both by application and the core. For example, if the application enables the channel after programming CTD=5, then the core starts processing the sixth descriptor. The address is obtained by adding a value of (8bytes*5=) 40(decimal) to DMAAddr. Reset: 6'h0 \\[2:0\\]: Reserved In Scatter-Gather DMA (DescDMA) Mode for Isochronous: \\[31:N\\]: DMA Address (DMAAddr) The start address must be 512-bytes aligned. This field holds the address of the 2*(nTD+1) bytes of locations in which the isochronous descriptors are present where N is based on nTD as follows: - \\[31:N\\]: Base Address - \\[N-1:3\\]: Offset - \\[2:0\\]: 000 For HS ISOC, if nTD is, - 7, N=6 - 15, N=7 - 31, N=8 - 63, N=9 - 127, N=10 - 255, N=11 For FS ISOC, if nTD is, - 1, N=4 - 3, N=5 - 7, N=6 - 15, N=7 - 31, N=8 - 63, N=9 \\[N-1:3\\]: Current Transfer Desc(CTD) CTD for isochronous is based on the current frame/(micro)frame value. Need to be set to zero by application. Reset: (N+1:3)'h0 \\[2:0\\]: Reserved"]
pub type DMAADDR_R = crate::FieldReader<u32>;
#[doc = "Field `DMAADDR` writer - In Buffer DMA Mode: \\[31:0\\]: DMA Address (DMAAddr) This field holds the start address in the external memory from which the data for the endpoint must be fetched or to which it must be stored. This register is incremented on every AHB transaction. Reset: X if not programmed as the register is in SPRAM. In Scatter-Gather DMA (DescDMA) Mode for Non-Isochronous: \\[31:9\\]: DMA Address (DMAAddr) The start address must be 512-bytes aligned. This field holds the start address of the 512 bytes page. The first descriptor in the list must be located in this address. The first descriptor may be or may not be ready. The core starts processing the list from the CTD value. \\[8:3\\]: Current Transfer Desc(CTD) This value is in terms of number of descriptors. The values can be from 0 to 63. - 0 - 1 descriptor. - 63 - 64 descriptors. This field indicates the current descriptor processed in the list. This field is updated both by application and the core. For example, if the application enables the channel after programming CTD=5, then the core starts processing the sixth descriptor. The address is obtained by adding a value of (8bytes*5=) 40(decimal) to DMAAddr. Reset: 6'h0 \\[2:0\\]: Reserved In Scatter-Gather DMA (DescDMA) Mode for Isochronous: \\[31:N\\]: DMA Address (DMAAddr) The start address must be 512-bytes aligned. This field holds the address of the 2*(nTD+1) bytes of locations in which the isochronous descriptors are present where N is based on nTD as follows: - \\[31:N\\]: Base Address - \\[N-1:3\\]: Offset - \\[2:0\\]: 000 For HS ISOC, if nTD is, - 7, N=6 - 15, N=7 - 31, N=8 - 63, N=9 - 127, N=10 - 255, N=11 For FS ISOC, if nTD is, - 1, N=4 - 3, N=5 - 7, N=6 - 15, N=7 - 31, N=8 - 63, N=9 \\[N-1:3\\]: Current Transfer Desc(CTD) CTD for isochronous is based on the current frame/(micro)frame value. Need to be set to zero by application. Reset: (N+1:3)'h0 \\[2:0\\]: Reserved"]
pub type DMAADDR_W<'a, REG> = crate::FieldWriter<'a, REG, 32, u32>;
impl R {
    #[doc = "Bits 0:31 - In Buffer DMA Mode: \\[31:0\\]: DMA Address (DMAAddr) This field holds the start address in the external memory from which the data for the endpoint must be fetched or to which it must be stored. This register is incremented on every AHB transaction. Reset: X if not programmed as the register is in SPRAM. In Scatter-Gather DMA (DescDMA) Mode for Non-Isochronous: \\[31:9\\]: DMA Address (DMAAddr) The start address must be 512-bytes aligned. This field holds the start address of the 512 bytes page. The first descriptor in the list must be located in this address. The first descriptor may be or may not be ready. The core starts processing the list from the CTD value. \\[8:3\\]: Current Transfer Desc(CTD) This value is in terms of number of descriptors. The values can be from 0 to 63. - 0 - 1 descriptor. - 63 - 64 descriptors. This field indicates the current descriptor processed in the list. This field is updated both by application and the core. For example, if the application enables the channel after programming CTD=5, then the core starts processing the sixth descriptor. The address is obtained by adding a value of (8bytes*5=) 40(decimal) to DMAAddr. Reset: 6'h0 \\[2:0\\]: Reserved In Scatter-Gather DMA (DescDMA) Mode for Isochronous: \\[31:N\\]: DMA Address (DMAAddr) The start address must be 512-bytes aligned. This field holds the address of the 2*(nTD+1) bytes of locations in which the isochronous descriptors are present where N is based on nTD as follows: - \\[31:N\\]: Base Address - \\[N-1:3\\]: Offset - \\[2:0\\]: 000 For HS ISOC, if nTD is, - 7, N=6 - 15, N=7 - 31, N=8 - 63, N=9 - 127, N=10 - 255, N=11 For FS ISOC, if nTD is, - 1, N=4 - 3, N=5 - 7, N=6 - 15, N=7 - 31, N=8 - 63, N=9 \\[N-1:3\\]: Current Transfer Desc(CTD) CTD for isochronous is based on the current frame/(micro)frame value. Need to be set to zero by application. Reset: (N+1:3)'h0 \\[2:0\\]: Reserved"]
    #[inline(always)]
    pub fn dmaaddr(&self) -> DMAADDR_R {
        DMAADDR_R::new(self.bits)
    }
}
#[cfg(feature = "impl-register-debug")]
impl core::fmt::Debug for R {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("HCDMA13")
            .field("dmaaddr", &self.dmaaddr())
            .finish()
    }
}
impl W {
    #[doc = "Bits 0:31 - In Buffer DMA Mode: \\[31:0\\]: DMA Address (DMAAddr) This field holds the start address in the external memory from which the data for the endpoint must be fetched or to which it must be stored. This register is incremented on every AHB transaction. Reset: X if not programmed as the register is in SPRAM. In Scatter-Gather DMA (DescDMA) Mode for Non-Isochronous: \\[31:9\\]: DMA Address (DMAAddr) The start address must be 512-bytes aligned. This field holds the start address of the 512 bytes page. The first descriptor in the list must be located in this address. The first descriptor may be or may not be ready. The core starts processing the list from the CTD value. \\[8:3\\]: Current Transfer Desc(CTD) This value is in terms of number of descriptors. The values can be from 0 to 63. - 0 - 1 descriptor. - 63 - 64 descriptors. This field indicates the current descriptor processed in the list. This field is updated both by application and the core. For example, if the application enables the channel after programming CTD=5, then the core starts processing the sixth descriptor. The address is obtained by adding a value of (8bytes*5=) 40(decimal) to DMAAddr. Reset: 6'h0 \\[2:0\\]: Reserved In Scatter-Gather DMA (DescDMA) Mode for Isochronous: \\[31:N\\]: DMA Address (DMAAddr) The start address must be 512-bytes aligned. This field holds the address of the 2*(nTD+1) bytes of locations in which the isochronous descriptors are present where N is based on nTD as follows: - \\[31:N\\]: Base Address - \\[N-1:3\\]: Offset - \\[2:0\\]: 000 For HS ISOC, if nTD is, - 7, N=6 - 15, N=7 - 31, N=8 - 63, N=9 - 127, N=10 - 255, N=11 For FS ISOC, if nTD is, - 1, N=4 - 3, N=5 - 7, N=6 - 15, N=7 - 31, N=8 - 63, N=9 \\[N-1:3\\]: Current Transfer Desc(CTD) CTD for isochronous is based on the current frame/(micro)frame value. Need to be set to zero by application. Reset: (N+1:3)'h0 \\[2:0\\]: Reserved"]
    #[inline(always)]
    pub fn dmaaddr(&mut self) -> DMAADDR_W<'_, HCDMA13_SPEC> {
        DMAADDR_W::new(self, 0)
    }
}
#[doc = "This register is used by the OTG host in the internal DMA mode to maintain the current buffer pointer for IN/OUT transactions. The starting DMA address must be DWORD-aligned.\n\nYou can [`read`](crate::Reg::read) this register and get [`hcdma13::R`](R). You can [`reset`](crate::Reg::reset), [`write`](crate::Reg::write), [`write_with_zero`](crate::Reg::write_with_zero) this register using [`hcdma13::W`](W). You can also [`modify`](crate::Reg::modify) this register. See [API](https://docs.rs/svd2rust/#read--modify--write-api)."]
pub struct HCDMA13_SPEC;
impl crate::RegisterSpec for HCDMA13_SPEC {
    type Ux = u32;
}
#[doc = "`read()` method returns [`hcdma13::R`](R) reader structure"]
impl crate::Readable for HCDMA13_SPEC {}
#[doc = "`write(|w| ..)` method takes [`hcdma13::W`](W) writer structure"]
impl crate::Writable for HCDMA13_SPEC {
    type Safety = crate::Unsafe;
}
#[doc = "`reset()` method sets HCDMA13 to value 0"]
impl crate::Resettable for HCDMA13_SPEC {}
