#![doc = "Peripheral access API for ESP32-P4-LP microcontrollers (generated using svd2rust v0.37.1 (f74f0b3 2026-04-17))\n\nYou can find an overview of the generated API [here].\n\nAPI features to be included in the [next] svd2rust release can be generated by cloning the svd2rust [repository], checking out the above commit, and running `cargo doc --open`.\n\n[here]: https://docs.rs/svd2rust/0.37.1/svd2rust/#peripheral-api\n[next]: https://github.com/rust-embedded/svd2rust/blob/master/CHANGELOG.md#unreleased\n[repository]: https://github.com/rust-embedded/svd2rust"]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![doc(html_logo_url = "https://avatars.githubusercontent.com/u/46717278")]
#![no_std]
#![cfg_attr(docsrs, feature(doc_cfg))]
#[doc = r"Number available in the NVIC for configuring priority"]
pub const NVIC_PRIO_BITS: u8 = 0;
#[allow(unused_imports)]
use generic::*;
#[doc = r"Common register and bit access and modify traits"]
pub mod generic;
#[cfg(feature = "rt")]
extern "C" {
    fn LP_SW();
    fn LP_UART();
    fn LP_SPI();
    fn LP_TRNG();
    fn LP_I2C();
    fn LP_IO();
    fn LP_ADC();
    fn LP_TOUCH();
    fn LP_TSENS();
    fn LP_EFUSE();
    fn LP_SYSREG();
    fn LP_ANA_PERI();
    fn LP_PMU();
    fn LP_MAILBOX();
    fn LP_TIMER();
    fn LP_WDT();
    fn LP_RTC();
}
#[doc(hidden)]
#[repr(C)]
pub union Vector {
    pub _handler: unsafe extern "C" fn(),
    pub _reserved: usize,
}
#[cfg(feature = "rt")]
#[doc(hidden)]
#[link_section = ".rwtext"]
#[no_mangle]
pub static __EXTERNAL_INTERRUPTS: [Vector; 29] = [
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: LP_SW },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: LP_UART },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: LP_SPI },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: LP_TRNG },
    Vector { _handler: LP_I2C },
    Vector { _handler: LP_IO },
    Vector { _handler: LP_ADC },
    Vector { _handler: LP_TOUCH },
    Vector { _handler: LP_TSENS },
    Vector { _handler: LP_EFUSE },
    Vector {
        _handler: LP_SYSREG,
    },
    Vector {
        _handler: LP_ANA_PERI,
    },
    Vector { _handler: LP_PMU },
    Vector {
        _handler: LP_MAILBOX,
    },
    Vector { _handler: LP_TIMER },
    Vector { _handler: LP_WDT },
    Vector { _handler: LP_RTC },
];
#[doc(hidden)]
pub mod interrupt;
pub use self::interrupt::Interrupt;
#[doc = "HP2LP_PERI_PMS"]
pub type HP2LP_PERI_PMS = crate::Periph<hp2lp_peri_pms::RegisterBlock, 0x5012_e800>;
impl core::fmt::Debug for HP2LP_PERI_PMS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("HP2LP_PERI_PMS").finish()
    }
}
#[doc = "HP2LP_PERI_PMS"]
pub mod hp2lp_peri_pms;
#[doc = "LP2HP_PERI_PMS"]
pub type LP2HP_PERI_PMS = crate::Periph<lp2hp_peri_pms::RegisterBlock, 0x500a_5800>;
impl core::fmt::Debug for LP2HP_PERI_PMS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("LP2HP_PERI_PMS").finish()
    }
}
#[doc = "LP2HP_PERI_PMS"]
pub mod lp2hp_peri_pms;
#[doc = "Low-power Analog to Digital Converter"]
pub type LP_ADC = crate::Periph<lp_adc::RegisterBlock, 0x5012_7000>;
impl core::fmt::Debug for LP_ADC {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("LP_ADC").finish()
    }
}
#[doc = "Low-power Analog to Digital Converter"]
pub mod lp_adc;
#[doc = "LP_ANA_PERI Peripheral"]
pub type LP_ANA_PERI = crate::Periph<lp_ana_peri::RegisterBlock, 0x5011_3000>;
impl core::fmt::Debug for LP_ANA_PERI {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("LP_ANA_PERI").finish()
    }
}
#[doc = "LP_ANA_PERI Peripheral"]
pub mod lp_ana_peri;
#[doc = "LP_AON_CLKRST Peripheral"]
pub type LP_AON_CLKRST = crate::Periph<lp_aon_clkrst::RegisterBlock, 0x5011_1000>;
impl core::fmt::Debug for LP_AON_CLKRST {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("LP_AON_CLKRST").finish()
    }
}
#[doc = "LP_AON_CLKRST Peripheral"]
pub mod lp_aon_clkrst;
#[doc = "Low-power General Purpose Input/Output"]
pub type LP_GPIO = crate::Periph<lp_gpio::RegisterBlock, 0x5012_a000>;
impl core::fmt::Debug for LP_GPIO {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("LP_GPIO").finish()
    }
}
#[doc = "Low-power General Purpose Input/Output"]
pub mod lp_gpio;
#[doc = "LP_HUK Peripheral"]
pub type LP_HUK = crate::Periph<lp_huk::RegisterBlock, 0x5011_4000>;
impl core::fmt::Debug for LP_HUK {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("LP_HUK").finish()
    }
}
#[doc = "LP_HUK Peripheral"]
pub mod lp_huk;
#[doc = "LP_I2C0"]
pub type LP_I2C0 = crate::Periph<lp_i2c0::RegisterBlock, 0x5012_2000>;
impl core::fmt::Debug for LP_I2C0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("LP_I2C0").finish()
    }
}
#[doc = "LP_I2C0"]
pub mod lp_i2c0;
#[doc = "LP_I2C_ANA_MST Peripheral"]
pub type LP_I2C_ANA_MST = crate::Periph<lp_i2c_ana_mst::RegisterBlock, 0x5012_4000>;
impl core::fmt::Debug for LP_I2C_ANA_MST {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("LP_I2C_ANA_MST").finish()
    }
}
#[doc = "LP_I2C_ANA_MST Peripheral"]
pub mod lp_i2c_ana_mst;
#[doc = "Low-power I2S (Inter-IC Sound) Controller 0"]
pub type LP_I2S0 = crate::Periph<lp_i2s0::RegisterBlock, 0x5012_5000>;
impl core::fmt::Debug for LP_I2S0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("LP_I2S0").finish()
    }
}
#[doc = "Low-power I2S (Inter-IC Sound) Controller 0"]
pub mod lp_i2s0;
#[doc = "Low-power Interrupt Controller"]
pub type LP_INTR = crate::Periph<lp_intr::RegisterBlock, 0x5012_c000>;
impl core::fmt::Debug for LP_INTR {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("LP_INTR").finish()
    }
}
#[doc = "Low-power Interrupt Controller"]
pub mod lp_intr;
#[doc = "Low-power Input/Output Multiplexer"]
pub type LP_IO_MUX = crate::Periph<lp_io_mux::RegisterBlock, 0x5012_b000>;
impl core::fmt::Debug for LP_IO_MUX {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("LP_IO_MUX").finish()
    }
}
#[doc = "Low-power Input/Output Multiplexer"]
pub mod lp_io_mux;
#[doc = "LP_MAILBOX"]
pub type LP_MAILBOX = crate::Periph<lp_mailbox::RegisterBlock, 0x5011_8000>;
impl core::fmt::Debug for LP_MAILBOX {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("LP_MAILBOX").finish()
    }
}
#[doc = "LP_MAILBOX"]
pub mod lp_mailbox;
#[doc = "LP_PERI Peripheral"]
pub type LP_PERI = crate::Periph<lp_peri::RegisterBlock, 0x5012_0000>;
impl core::fmt::Debug for LP_PERI {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("LP_PERI").finish()
    }
}
#[doc = "LP_PERI Peripheral"]
pub mod lp_peri;
#[doc = "LP_PERI_PMS"]
pub type LP_PERI_PMS = crate::Periph<lp_peri_pms::RegisterBlock, 0x5012_e000>;
impl core::fmt::Debug for LP_PERI_PMS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("LP_PERI_PMS").finish()
    }
}
#[doc = "LP_PERI_PMS"]
pub mod lp_peri_pms;
#[doc = "LP_SPI"]
pub type LP_SPI = crate::Periph<lp_spi::RegisterBlock, 0x5012_3000>;
impl core::fmt::Debug for LP_SPI {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("LP_SPI").finish()
    }
}
#[doc = "LP_SPI"]
pub mod lp_spi;
#[doc = "LP_SYS Peripheral"]
pub type LP_SYS = crate::Periph<lp_sys::RegisterBlock, 0x5011_0000>;
impl core::fmt::Debug for LP_SYS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("LP_SYS").finish()
    }
}
#[doc = "LP_SYS Peripheral"]
pub mod lp_sys;
#[doc = "Low-power Timer"]
pub type LP_TIMER = crate::Periph<lp_timer::RegisterBlock, 0x5011_2000>;
impl core::fmt::Debug for LP_TIMER {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("LP_TIMER").finish()
    }
}
#[doc = "Low-power Timer"]
pub mod lp_timer;
#[doc = "LP_TOUCH Peripheral"]
pub type LP_TOUCH = crate::Periph<lp_touch::RegisterBlock, 0x5012_8000>;
impl core::fmt::Debug for LP_TOUCH {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("LP_TOUCH").finish()
    }
}
#[doc = "LP_TOUCH Peripheral"]
pub mod lp_touch;
#[doc = "LP_TRNG"]
pub type LP_TRNG = crate::Periph<lp_trng::RegisterBlock, 0x5012_6000>;
impl core::fmt::Debug for LP_TRNG {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("LP_TRNG").finish()
    }
}
#[doc = "LP_TRNG"]
pub mod lp_trng;
#[doc = "Low-power Temperature Sensor"]
pub type LP_TSENS = crate::Periph<lp_tsens::RegisterBlock, 0x5012_f000>;
impl core::fmt::Debug for LP_TSENS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("LP_TSENS").finish()
    }
}
#[doc = "Low-power Temperature Sensor"]
pub mod lp_tsens;
#[doc = "Low-power UART (Universal Asynchronous Receiver-Transmitter) Controller"]
pub type LP_UART = crate::Periph<lp_uart::RegisterBlock, 0x5012_1000>;
impl core::fmt::Debug for LP_UART {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("LP_UART").finish()
    }
}
#[doc = "Low-power UART (Universal Asynchronous Receiver-Transmitter) Controller"]
pub mod lp_uart;
#[doc = "Low-power Watchdog Timer"]
pub type LP_WDT = crate::Periph<lp_wdt::RegisterBlock, 0x5011_6000>;
impl core::fmt::Debug for LP_WDT {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("LP_WDT").finish()
    }
}
#[doc = "Low-power Watchdog Timer"]
pub mod lp_wdt;
#[doc = "PAU Peripheral"]
pub type PAU = crate::Periph<pau::RegisterBlock, 0x6009_3000>;
impl core::fmt::Debug for PAU {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("PAU").finish()
    }
}
#[doc = "PAU Peripheral"]
pub mod pau;
#[doc = "PMU"]
pub type PMU = crate::Periph<pmu::RegisterBlock, 0x5011_5000>;
impl core::fmt::Debug for PMU {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("PMU").finish()
    }
}
#[doc = "PMU"]
pub mod pmu;
#[no_mangle]
static mut DEVICE_PERIPHERALS: bool = false;
#[doc = r" All the peripherals."]
#[allow(non_snake_case)]
pub struct Peripherals {
    #[doc = "HP2LP_PERI_PMS"]
    pub HP2LP_PERI_PMS: HP2LP_PERI_PMS,
    #[doc = "LP2HP_PERI_PMS"]
    pub LP2HP_PERI_PMS: LP2HP_PERI_PMS,
    #[doc = "LP_ADC"]
    pub LP_ADC: LP_ADC,
    #[doc = "LP_ANA_PERI"]
    pub LP_ANA_PERI: LP_ANA_PERI,
    #[doc = "LP_AON_CLKRST"]
    pub LP_AON_CLKRST: LP_AON_CLKRST,
    #[doc = "LP_GPIO"]
    pub LP_GPIO: LP_GPIO,
    #[doc = "LP_HUK"]
    pub LP_HUK: LP_HUK,
    #[doc = "LP_I2C0"]
    pub LP_I2C0: LP_I2C0,
    #[doc = "LP_I2C_ANA_MST"]
    pub LP_I2C_ANA_MST: LP_I2C_ANA_MST,
    #[doc = "LP_I2S0"]
    pub LP_I2S0: LP_I2S0,
    #[doc = "LP_INTR"]
    pub LP_INTR: LP_INTR,
    #[doc = "LP_IO_MUX"]
    pub LP_IO_MUX: LP_IO_MUX,
    #[doc = "LP_MAILBOX"]
    pub LP_MAILBOX: LP_MAILBOX,
    #[doc = "LP_PERI"]
    pub LP_PERI: LP_PERI,
    #[doc = "LP_PERI_PMS"]
    pub LP_PERI_PMS: LP_PERI_PMS,
    #[doc = "LP_SPI"]
    pub LP_SPI: LP_SPI,
    #[doc = "LP_SYS"]
    pub LP_SYS: LP_SYS,
    #[doc = "LP_TIMER"]
    pub LP_TIMER: LP_TIMER,
    #[doc = "LP_TOUCH"]
    pub LP_TOUCH: LP_TOUCH,
    #[doc = "LP_TRNG"]
    pub LP_TRNG: LP_TRNG,
    #[doc = "LP_TSENS"]
    pub LP_TSENS: LP_TSENS,
    #[doc = "LP_UART"]
    pub LP_UART: LP_UART,
    #[doc = "LP_WDT"]
    pub LP_WDT: LP_WDT,
    #[doc = "PAU"]
    pub PAU: PAU,
    #[doc = "PMU"]
    pub PMU: PMU,
}
impl Peripherals {
    #[doc = r" Returns all the peripherals *once*."]
    #[cfg(feature = "critical-section")]
    #[inline]
    pub fn take() -> Option<Self> {
        critical_section::with(|_| {
            if unsafe { DEVICE_PERIPHERALS } {
                return None;
            }
            Some(unsafe { Peripherals::steal() })
        })
    }
    #[doc = r" Unchecked version of `Peripherals::take`."]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Each of the returned peripherals must be used at most once."]
    #[inline]
    pub unsafe fn steal() -> Self {
        DEVICE_PERIPHERALS = true;
        Peripherals {
            HP2LP_PERI_PMS: HP2LP_PERI_PMS::steal(),
            LP2HP_PERI_PMS: LP2HP_PERI_PMS::steal(),
            LP_ADC: LP_ADC::steal(),
            LP_ANA_PERI: LP_ANA_PERI::steal(),
            LP_AON_CLKRST: LP_AON_CLKRST::steal(),
            LP_GPIO: LP_GPIO::steal(),
            LP_HUK: LP_HUK::steal(),
            LP_I2C0: LP_I2C0::steal(),
            LP_I2C_ANA_MST: LP_I2C_ANA_MST::steal(),
            LP_I2S0: LP_I2S0::steal(),
            LP_INTR: LP_INTR::steal(),
            LP_IO_MUX: LP_IO_MUX::steal(),
            LP_MAILBOX: LP_MAILBOX::steal(),
            LP_PERI: LP_PERI::steal(),
            LP_PERI_PMS: LP_PERI_PMS::steal(),
            LP_SPI: LP_SPI::steal(),
            LP_SYS: LP_SYS::steal(),
            LP_TIMER: LP_TIMER::steal(),
            LP_TOUCH: LP_TOUCH::steal(),
            LP_TRNG: LP_TRNG::steal(),
            LP_TSENS: LP_TSENS::steal(),
            LP_UART: LP_UART::steal(),
            LP_WDT: LP_WDT::steal(),
            PAU: PAU::steal(),
            PMU: PMU::steal(),
        }
    }
}
