#[doc = r"Enumeration of all the interrupts."]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
#[repr(u16)]
pub enum Interrupt {
    #[doc = "0 - WIFI_MAC"]
    WIFI_MAC          = 0,
    #[doc = "1 - WIFI_MAC_NMI"]
    WIFI_MAC_NMI      = 1,
    #[doc = "2 - WIFI_PWR"]
    WIFI_PWR          = 2,
    #[doc = "3 - WIFI_BB"]
    WIFI_BB           = 3,
    #[doc = "4 - BT_MAC"]
    BT_MAC            = 4,
    #[doc = "5 - BT_BB"]
    BT_BB             = 5,
    #[doc = "6 - BT_BB_NMI"]
    BT_BB_NMI         = 6,
    #[doc = "7 - LP_TIMER"]
    LP_TIMER          = 7,
    #[doc = "8 - COEX"]
    COEX              = 8,
    #[doc = "9 - BLE_TIMER"]
    BLE_TIMER         = 9,
    #[doc = "10 - BLE_SEC"]
    BLE_SEC           = 10,
    #[doc = "11 - I2C_MST"]
    I2C_MST           = 11,
    #[doc = "12 - ZB_MAC"]
    ZB_MAC            = 12,
    #[doc = "13 - MODEM_APB_TIMEOUT"]
    MODEM_APB_TIMEOUT = 13,
    #[doc = "14 - BT_MAC_INT1"]
    BT_MAC_INT1       = 14,
    #[doc = "15 - PMU"]
    PMU               = 15,
    #[doc = "16 - EFUSE"]
    EFUSE             = 16,
    #[doc = "17 - LP_RTC_TIMER"]
    LP_RTC_TIMER      = 17,
    #[doc = "18 - LP_RTC_BLE_TIMER"]
    LP_RTC_BLE_TIMER  = 18,
    #[doc = "19 - LP_WDT"]
    LP_WDT            = 19,
    #[doc = "20 - TOUCH"]
    TOUCH             = 20,
    #[doc = "21 - HUK"]
    HUK               = 21,
    #[doc = "22 - LP_PERI_PMS"]
    LP_PERI_PMS       = 22,
    #[doc = "23 - FROM_CPU_INTR0"]
    FROM_CPU_INTR0    = 23,
    #[doc = "24 - FROM_CPU_INTR1"]
    FROM_CPU_INTR1    = 24,
    #[doc = "25 - FROM_CPU_INTR2"]
    FROM_CPU_INTR2    = 25,
    #[doc = "26 - FROM_CPU_INTR3"]
    FROM_CPU_INTR3    = 26,
    #[doc = "27 - BUS_MONITOR"]
    BUS_MONITOR       = 27,
    #[doc = "28 - CORE0_TRACE"]
    CORE0_TRACE       = 28,
    #[doc = "29 - CORE1_TRACE"]
    CORE1_TRACE       = 29,
    #[doc = "30 - CACHE"]
    CACHE             = 30,
    #[doc = "31 - CPU_PERI_TIMEOUT"]
    CPU_PERI_TIMEOUT  = 31,
    #[doc = "32 - GPIO"]
    GPIO              = 32,
    #[doc = "33 - GPIO_INTERRUPT_2"]
    GPIO_INTERRUPT_2  = 33,
    #[doc = "34 - PAU"]
    PAU               = 34,
    #[doc = "35 - HP_PERI_TIMEOUT"]
    HP_PERI_TIMEOUT   = 35,
    #[doc = "36 - HP_APM_M0"]
    HP_APM_M0         = 36,
    #[doc = "37 - HP_APM_M1"]
    HP_APM_M1         = 37,
    #[doc = "38 - HP_APM_M2"]
    HP_APM_M2         = 38,
    #[doc = "39 - HP_APM_M3"]
    HP_APM_M3         = 39,
    #[doc = "40 - HP_APM_M4"]
    HP_APM_M4         = 40,
    #[doc = "41 - HP_MEM_APM_M0"]
    HP_MEM_APM_M0     = 41,
    #[doc = "42 - HP_MEM_APM_M1"]
    HP_MEM_APM_M1     = 42,
    #[doc = "43 - HP_MEM_APM_M2"]
    HP_MEM_APM_M2     = 43,
    #[doc = "44 - HP_MEM_APM_M3"]
    HP_MEM_APM_M3     = 44,
    #[doc = "45 - CPU_APM_M0"]
    CPU_APM_M0        = 45,
    #[doc = "46 - CPU_APM_M1"]
    CPU_APM_M1        = 46,
    #[doc = "47 - CPU_APM_M2"]
    CPU_APM_M2        = 47,
    #[doc = "48 - CPU_APM_M3"]
    CPU_APM_M3        = 48,
    #[doc = "49 - HP_PERI_PMS"]
    HP_PERI_PMS       = 49,
    #[doc = "50 - MODEM_PERI_PMS"]
    MODEM_PERI_PMS    = 50,
    #[doc = "51 - CPU_PERI_PMS"]
    CPU_PERI_PMS      = 51,
    #[doc = "52 - MSPI"]
    MSPI              = 52,
    #[doc = "53 - I2S"]
    I2S               = 53,
    #[doc = "54 - UHCI0"]
    UHCI0             = 54,
    #[doc = "55 - UART0"]
    UART0             = 55,
    #[doc = "56 - UART1"]
    UART1             = 56,
    #[doc = "57 - LEDC"]
    LEDC              = 57,
    #[doc = "58 - TWAI0"]
    TWAI0             = 58,
    #[doc = "59 - TWAI0_TIMER"]
    TWAI0_TIMER       = 59,
    #[doc = "60 - USB_DEVICE"]
    USB_DEVICE        = 60,
    #[doc = "61 - RMT"]
    RMT               = 61,
    #[doc = "62 - I2C_EXT0"]
    I2C_EXT0          = 62,
    #[doc = "63 - I2C_EXT1"]
    I2C_EXT1          = 63,
    #[doc = "64 - TG0_T0"]
    TG0_T0            = 64,
    #[doc = "65 - TG0_WDT"]
    TG0_WDT           = 65,
    #[doc = "66 - TG1_T0"]
    TG1_T0            = 66,
    #[doc = "67 - TG1_WDT"]
    TG1_WDT           = 67,
    #[doc = "68 - SYSTIMER_TARGET0"]
    SYSTIMER_TARGET0  = 68,
    #[doc = "69 - SYSTIMER_TARGET1"]
    SYSTIMER_TARGET1  = 69,
    #[doc = "70 - SYSTIMER_TARGET2"]
    SYSTIMER_TARGET2  = 70,
    #[doc = "71 - APB_ADC"]
    APB_ADC           = 71,
    #[doc = "72 - MCPWM0"]
    MCPWM0            = 72,
    #[doc = "73 - MCPWM1"]
    MCPWM1            = 73,
    #[doc = "74 - PCNT"]
    PCNT              = 74,
    #[doc = "75 - PARL_IO_TX"]
    PARL_IO_TX        = 75,
    #[doc = "76 - PARL_IO_RX"]
    PARL_IO_RX        = 76,
    #[doc = "77 - USB_OTG11"]
    USB_OTG11         = 77,
    #[doc = "78 - ASRC_CHNL0"]
    ASRC_CHNL0        = 78,
    #[doc = "79 - ASRC_CHNL1"]
    ASRC_CHNL1        = 79,
    #[doc = "80 - ZERO_DET"]
    ZERO_DET          = 80,
    #[doc = "81 - DMA_IN_CH0"]
    DMA_IN_CH0        = 81,
    #[doc = "82 - DMA_IN_CH1"]
    DMA_IN_CH1        = 82,
    #[doc = "83 - DMA_IN_CH2"]
    DMA_IN_CH2        = 83,
    #[doc = "84 - DMA_IN_CH3"]
    DMA_IN_CH3        = 84,
    #[doc = "85 - DMA_IN_CH4"]
    DMA_IN_CH4        = 85,
    #[doc = "86 - DMA_OUT_CH0"]
    DMA_OUT_CH0       = 86,
    #[doc = "87 - DMA_OUT_CH1"]
    DMA_OUT_CH1       = 87,
    #[doc = "88 - DMA_OUT_CH2"]
    DMA_OUT_CH2       = 88,
    #[doc = "89 - DMA_OUT_CH3"]
    DMA_OUT_CH3       = 89,
    #[doc = "90 - DMA_OUT_CH4"]
    DMA_OUT_CH4       = 90,
    #[doc = "91 - GPSPI2"]
    GPSPI2            = 91,
    #[doc = "92 - GPSPI3"]
    GPSPI3            = 92,
    #[doc = "93 - AES"]
    AES               = 93,
    #[doc = "94 - SHA"]
    SHA               = 94,
    #[doc = "95 - ECC"]
    ECC               = 95,
    #[doc = "96 - ECDSA"]
    ECDSA             = 96,
    #[doc = "97 - KM"]
    KM                = 97,
}
#[doc = r" TryFromInterruptError"]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[derive(Debug, Copy, Clone)]
pub struct TryFromInterruptError(());
impl Interrupt {
    #[doc = r" Attempt to convert a given value into an `Interrupt`"]
    #[inline]
    pub fn try_from(value: u8) -> Result<Self, TryFromInterruptError> {
        match value {
            0 => Ok(Interrupt::WIFI_MAC),
            1 => Ok(Interrupt::WIFI_MAC_NMI),
            2 => Ok(Interrupt::WIFI_PWR),
            3 => Ok(Interrupt::WIFI_BB),
            4 => Ok(Interrupt::BT_MAC),
            5 => Ok(Interrupt::BT_BB),
            6 => Ok(Interrupt::BT_BB_NMI),
            7 => Ok(Interrupt::LP_TIMER),
            8 => Ok(Interrupt::COEX),
            9 => Ok(Interrupt::BLE_TIMER),
            10 => Ok(Interrupt::BLE_SEC),
            11 => Ok(Interrupt::I2C_MST),
            12 => Ok(Interrupt::ZB_MAC),
            13 => Ok(Interrupt::MODEM_APB_TIMEOUT),
            14 => Ok(Interrupt::BT_MAC_INT1),
            15 => Ok(Interrupt::PMU),
            16 => Ok(Interrupt::EFUSE),
            17 => Ok(Interrupt::LP_RTC_TIMER),
            18 => Ok(Interrupt::LP_RTC_BLE_TIMER),
            19 => Ok(Interrupt::LP_WDT),
            20 => Ok(Interrupt::TOUCH),
            21 => Ok(Interrupt::HUK),
            22 => Ok(Interrupt::LP_PERI_PMS),
            23 => Ok(Interrupt::FROM_CPU_INTR0),
            24 => Ok(Interrupt::FROM_CPU_INTR1),
            25 => Ok(Interrupt::FROM_CPU_INTR2),
            26 => Ok(Interrupt::FROM_CPU_INTR3),
            27 => Ok(Interrupt::BUS_MONITOR),
            28 => Ok(Interrupt::CORE0_TRACE),
            29 => Ok(Interrupt::CORE1_TRACE),
            30 => Ok(Interrupt::CACHE),
            31 => Ok(Interrupt::CPU_PERI_TIMEOUT),
            32 => Ok(Interrupt::GPIO),
            33 => Ok(Interrupt::GPIO_INTERRUPT_2),
            34 => Ok(Interrupt::PAU),
            35 => Ok(Interrupt::HP_PERI_TIMEOUT),
            36 => Ok(Interrupt::HP_APM_M0),
            37 => Ok(Interrupt::HP_APM_M1),
            38 => Ok(Interrupt::HP_APM_M2),
            39 => Ok(Interrupt::HP_APM_M3),
            40 => Ok(Interrupt::HP_APM_M4),
            41 => Ok(Interrupt::HP_MEM_APM_M0),
            42 => Ok(Interrupt::HP_MEM_APM_M1),
            43 => Ok(Interrupt::HP_MEM_APM_M2),
            44 => Ok(Interrupt::HP_MEM_APM_M3),
            45 => Ok(Interrupt::CPU_APM_M0),
            46 => Ok(Interrupt::CPU_APM_M1),
            47 => Ok(Interrupt::CPU_APM_M2),
            48 => Ok(Interrupt::CPU_APM_M3),
            49 => Ok(Interrupt::HP_PERI_PMS),
            50 => Ok(Interrupt::MODEM_PERI_PMS),
            51 => Ok(Interrupt::CPU_PERI_PMS),
            52 => Ok(Interrupt::MSPI),
            53 => Ok(Interrupt::I2S),
            54 => Ok(Interrupt::UHCI0),
            55 => Ok(Interrupt::UART0),
            56 => Ok(Interrupt::UART1),
            57 => Ok(Interrupt::LEDC),
            58 => Ok(Interrupt::TWAI0),
            59 => Ok(Interrupt::TWAI0_TIMER),
            60 => Ok(Interrupt::USB_DEVICE),
            61 => Ok(Interrupt::RMT),
            62 => Ok(Interrupt::I2C_EXT0),
            63 => Ok(Interrupt::I2C_EXT1),
            64 => Ok(Interrupt::TG0_T0),
            65 => Ok(Interrupt::TG0_WDT),
            66 => Ok(Interrupt::TG1_T0),
            67 => Ok(Interrupt::TG1_WDT),
            68 => Ok(Interrupt::SYSTIMER_TARGET0),
            69 => Ok(Interrupt::SYSTIMER_TARGET1),
            70 => Ok(Interrupt::SYSTIMER_TARGET2),
            71 => Ok(Interrupt::APB_ADC),
            72 => Ok(Interrupt::MCPWM0),
            73 => Ok(Interrupt::MCPWM1),
            74 => Ok(Interrupt::PCNT),
            75 => Ok(Interrupt::PARL_IO_TX),
            76 => Ok(Interrupt::PARL_IO_RX),
            77 => Ok(Interrupt::USB_OTG11),
            78 => Ok(Interrupt::ASRC_CHNL0),
            79 => Ok(Interrupt::ASRC_CHNL1),
            80 => Ok(Interrupt::ZERO_DET),
            81 => Ok(Interrupt::DMA_IN_CH0),
            82 => Ok(Interrupt::DMA_IN_CH1),
            83 => Ok(Interrupt::DMA_IN_CH2),
            84 => Ok(Interrupt::DMA_IN_CH3),
            85 => Ok(Interrupt::DMA_IN_CH4),
            86 => Ok(Interrupt::DMA_OUT_CH0),
            87 => Ok(Interrupt::DMA_OUT_CH1),
            88 => Ok(Interrupt::DMA_OUT_CH2),
            89 => Ok(Interrupt::DMA_OUT_CH3),
            90 => Ok(Interrupt::DMA_OUT_CH4),
            91 => Ok(Interrupt::GPSPI2),
            92 => Ok(Interrupt::GPSPI3),
            93 => Ok(Interrupt::AES),
            94 => Ok(Interrupt::SHA),
            95 => Ok(Interrupt::ECC),
            96 => Ok(Interrupt::ECDSA),
            97 => Ok(Interrupt::KM),
            _ => Err(TryFromInterruptError(())),
        }
    }
}
#[cfg(feature = "rt")]
#[macro_export]
#[doc = r" Assigns a handler to an interrupt"]
#[doc = r""]
#[doc = r" This macro takes two arguments: the name of an interrupt and the path to the"]
#[doc = r" function that will be used as the handler of that interrupt. That function"]
#[doc = r" must have signature `fn()`."]
#[doc = r""]
#[doc = r" Optionally, a third argument may be used to declare interrupt local data."]
#[doc = r" The handler will have exclusive access to these *local* variables on each"]
#[doc = r" invocation. If the third argument is used then the signature of the handler"]
#[doc = r" function must be `fn(&mut $NAME::Locals)` where `$NAME` is the first argument"]
#[doc = r" passed to the macro."]
#[doc = r""]
#[doc = r" # Example"]
#[doc = r""]
#[doc = r" ``` ignore"]
#[doc = r" interrupt!(TIM2, periodic);"]
#[doc = r""]
#[doc = r" fn periodic() {"]
#[doc = r#"     print!(".");"#]
#[doc = r" }"]
#[doc = r""]
#[doc = r" interrupt!(TIM3, tick, locals: {"]
#[doc = r"     tick: bool = false;"]
#[doc = r" });"]
#[doc = r""]
#[doc = r" fn tick(locals: &mut TIM3::Locals) {"]
#[doc = r"     locals.tick = !locals.tick;"]
#[doc = r""]
#[doc = r"     if locals.tick {"]
#[doc = r#"         println!("Tick");"#]
#[doc = r"     } else {"]
#[doc = r#"         println!("Tock");"#]
#[doc = r"     }"]
#[doc = r" }"]
#[doc = r" ```"]
macro_rules ! interrupt { ($ NAME : ident , $ path : path , locals : { $ ($ lvar : ident : $ lty : ty = $ lval : expr ;) * }) => { # [allow (non_snake_case)] mod $ NAME { pub struct Locals { $ (pub $ lvar : $ lty ,) * } } # [allow (non_snake_case)] # [no_mangle] pub extern "C" fn $ NAME () { let _ = $ crate :: interrupt :: Interrupt :: $ NAME ; static mut LOCALS : self :: $ NAME :: Locals = self :: $ NAME :: Locals { $ ($ lvar : $ lval ,) * } ; let f : fn (& mut self :: $ NAME :: Locals) = $ path ; f (unsafe { & mut LOCALS }) ; } } ; ($ NAME : ident , $ path : path) => { # [allow (non_snake_case)] # [no_mangle] pub extern "C" fn $ NAME () { let _ = $ crate :: interrupt :: Interrupt :: $ NAME ; let f : fn () = $ path ; f () ; } } }
