#[doc = "Register `QUERY_ERROR` reader"]
pub type R = crate::R<QUERY_ERROR_SPEC>;
#[doc = "Field `QUREY_CHECK` reader - Represents whether or not an HMAC key matches the purpose. \\\\0: Match \\\\1: Error"]
pub type QUREY_CHECK_R = crate::BitReader;
impl R {
    #[doc = "Bit 0 - Represents whether or not an HMAC key matches the purpose. \\\\0: Match \\\\1: Error"]
    #[inline(always)]
    pub fn qurey_check(&self) -> QUREY_CHECK_R {
        QUREY_CHECK_R::new((self.bits & 1) != 0)
    }
}
#[cfg(feature = "impl-register-debug")]
impl core::fmt::Debug for R {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("QUERY_ERROR")
            .field("qurey_check", &self.qurey_check())
            .finish()
    }
}
#[doc = "Stores matching results between keys generated by users and corresponding purposes\n\nYou can [`read`](crate::Reg::read) this register and get [`query_error::R`](R). See [API](https://docs.rs/svd2rust/#read--modify--write-api)."]
pub struct QUERY_ERROR_SPEC;
impl crate::RegisterSpec for QUERY_ERROR_SPEC {
    type Ux = u32;
}
#[doc = "`read()` method returns [`query_error::R`](R) reader structure"]
impl crate::Readable for QUERY_ERROR_SPEC {}
#[doc = "`reset()` method sets QUERY_ERROR to value 0"]
impl crate::Resettable for QUERY_ERROR_SPEC {}
