name: CI

on:
  pull_request:
    branches:
      - main
  push:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# Cancel any currently running workflows from the same PR, branch, or
# tag when a new workflow is triggered.
#
# https://stackoverflow.com/a/66336834
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  # --------------------------------------------------------------------------
  # Check

  check-riscv:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        chip: [esp32c2, esp32c3, esp32c6, esp32h2]

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
        with:
          targets: riscv32imc-unknown-none-elf,riscv32imac-unknown-none-elf
          components: rust-src
      - uses: Swatinem/rust-cache@v2

      - name: generate pac
        run: cargo run --manifest-path=xtask/Cargo.toml -- generate ${{ matrix.chip }}
      - name: build pac
        run: cd ${{ matrix.chip }} && cargo check --all-targets

  check-xtensa:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        chip: [esp32, esp32s2, esp32s3]

    steps:
      - uses: actions/checkout@v3
      - uses: esp-rs/xtensa-toolchain@v1.5
        with:
          ldproxy: false
          buildtargets: ${{ matrix.chip }}
          override: false
      - uses: Swatinem/rust-cache@v2

      - name: generate pac
        run: cargo run --manifest-path=xtask/Cargo.toml -- generate ${{ matrix.chip }}
      - name: build pac
        run: cd ${{ matrix.chip }} && cargo check --all-targets

  # --------------------------------------------------------------------------
  # MSRV

  msrv-riscv:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        chip: [esp32c2, esp32c3, esp32c6, esp32h2]

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
        with:
          targets: riscv32imc-unknown-none-elf,riscv32imac-unknown-none-elf
          components: rust-src
      - uses: dtolnay/rust-toolchain@1.65.0
        with:
          targets: riscv32imc-unknown-none-elf,riscv32imac-unknown-none-elf
          components: rust-src
      - uses: Swatinem/rust-cache@v2

      - name: generate pac
        run: cargo +nightly run --manifest-path=xtask/Cargo.toml -- generate ${{ matrix.chip }}
      - name: build pac
        run: cd ${{ matrix.chip }} && cargo +1.65.0 check --all-targets

  msrv-xtensa:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        chip: [esp32, esp32s2, esp32s3]

    steps:
      - uses: actions/checkout@v3
      - uses: esp-rs/xtensa-toolchain@v1.5
        with:
          ldproxy: false
          buildtargets: ${{ matrix.chip }}
          version: "1.65.0"
          override: false
      - uses: Swatinem/rust-cache@v2

      - name: generate pac
        run: cargo run --manifest-path=xtask/Cargo.toml -- generate ${{ matrix.chip }}
      - name: build pac
        run: cd ${{ matrix.chip }} && cargo check --all-targets
