on:
  pull_request:
    branches:
      - main
  push:
  workflow_dispatch:

name: CI

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  # --------------------------------------------------------------------------
  # Check

  check-riscv:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        chip: [esp32c2, esp32c3, esp32c6, esp32h2]

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          target: riscv32imc-unknown-none-elf
          toolchain: nightly
          default: true
          components: rust-src
      - uses: Swatinem/rust-cache@v2

      - name: generate pac
        run: cargo run --manifest-path=xtask/Cargo.toml -- --generate-only ${{ matrix.chip }}
      - name: build pac
        run: cd ${{ matrix.chip }} && cargo check

  check-xtensa:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        chip: [esp32, esp32s2, esp32s3]

    steps:
      - uses: actions/checkout@v3
      - uses: esp-rs/xtensa-toolchain@v1.5
        with:
          ldproxy: false
          buildtargets: ${{ matrix.chip }}
          override: false
      - uses: Swatinem/rust-cache@v2

      - name: generate pac
        run: cargo run --manifest-path=xtask/Cargo.toml -- --generate-only ${{ matrix.chip }}
      - name: build pac
        run: cd ${{ matrix.chip }} && cargo check

  # --------------------------------------------------------------------------
  # MSRV

  msrv-riscv:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        chip: [esp32c2, esp32c3, esp32c6, esp32h2]

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          target: riscv32imc-unknown-none-elf
          toolchain: nightly
          default: true
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          target: riscv32imc-unknown-none-elf
          toolchain: "1.60.0"
          components: rust-src
      - uses: Swatinem/rust-cache@v2

      - name: generate pac
        run: cargo run --manifest-path=xtask/Cargo.toml -- --generate-only ${{ matrix.chip }}
      - name: build pac
        run: cd ${{ matrix.chip }} && cargo +1.60.0 check

  msrv-xtensa:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        chip: [esp32, esp32s2, esp32s3]

    steps:
      - uses: actions/checkout@v3
      - uses: esp-rs/xtensa-toolchain@v1.5
        with:
          ldproxy: false
          buildtargets: ${{ matrix.chip }}
          version: "1.60.0"
          override: false
      - uses: Swatinem/rust-cache@v2

      - name: generate pac
        run: cargo run --manifest-path=xtask/Cargo.toml -- --generate-only ${{ matrix.chip }}
      - name: build pac
        run: cd ${{ matrix.chip }} && cargo check
