name: CI

on:
  pull_request:
    paths-ignore:
      - "**/README.md"
  push:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# Cancel any currently running workflows from the same PR, branch, or
# tag when a new workflow is triggered.
#
# https://stackoverflow.com/a/66336834
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  # --------------------------------------------------------------------------

  check:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        build: [
            # Xtensa:
            { package: "esp32",   target: "xtensa-esp32-none-elf" },
            { package: "esp32s2", target: "xtensa-esp32s2-none-elf" },
            { package: "esp32s3", target: "xtensa-esp32s3-none-elf" },
  
            # RISC-V:
            { package: "esp32c2", target: "riscv32imc-unknown-none-elf" },
            { package: "esp32c3", target: "riscv32imc-unknown-none-elf" },
            { package: "esp32c6", target: "riscv32imac-unknown-none-elf" },
            { package: "esp32h2", target: "riscv32imac-unknown-none-elf" },
            { package: "esp32p4", target: "riscv32imafc-unknown-none-elf" },

            # RISC-V (Ultra) Low-Power:
            { package: "esp32c6-lp",  target: "riscv32imac-unknown-none-elf" },
            { package: "esp32s2-ulp", target: "riscv32imc-unknown-none-elf" },
            { package: "esp32s3-ulp", target: "riscv32imc-unknown-none-elf" },
          ]

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/check
        with:
          msrv: "1.76.0"
          package: ${{ matrix.build.package }}
          target: ${{ matrix.build.target }}
